"""Warm-up drill generation + deterministic pass/fail judging (010, P2c).

A 30–60 s oral drill of 3 items, generated by the LLM from the learner's top
recurring error, with IMMEDIATE per-item pass/fail. Generation reuses the injected
``LLMEngine`` + the shared JSON recovery ladder; JUDGING is deterministic (no LLM):
an item passes iff the transcribed response contains the corrected form and not the
error form; an empty/garbage/silent response is `incomplete`, not a fail (FR-016).
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path
from typing import Literal

from speakloop.config import paths
from speakloop.feedback.grammar_analyzer import _extract_json
from speakloop.llm import LLMEngine, LLMEngineError

_DRILL_MAX_TOKENS = 512
_DRILL_TEMPERATURE = 0.4
NUM_ITEMS = 3
_MIN_RESPONSE_WORDS = 2  # below this → incomplete, not a fail

_DEFAULT = Path(__file__).parent / "drill_prompt_default.txt"
_WORD_RE = re.compile(r"[A-Za-z0-9']+")

DrillResult = Literal["pass", "fail", "incomplete"]


@dataclass(frozen=True)
class DrillItem:
    target_sentence: str
    corrected_form: str
    error_form: str


def load_drill_prompt() -> tuple[str, Path]:
    """Seed + read the editable drill prompt (~/.speakloop/openrouter_drill_prompt.txt)."""
    target = paths.openrouter_drill_prompt_path()
    if not target.exists():
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(_DEFAULT.read_text(encoding="utf-8"), encoding="utf-8")
    return target.read_text(encoding="utf-8"), target


def generate_drill(top_error_label: str, llm: LLMEngine, *, system_prompt: str) -> list[DrillItem]:
    """Generate the 3 drill items for ``top_error_label``. Raises LLMEngineError on
    empty/failed response (the coordinator then skips the warm-up gracefully)."""
    raw = llm.generate(
        system_prompt,
        f"The learner's recurring grammar error to drill: {top_error_label.strip()}",
        max_tokens=_DRILL_MAX_TOKENS,
        temperature=_DRILL_TEMPERATURE,
    )
    if not raw or not raw.strip():
        raise LLMEngineError("Drill generator returned an empty response.")
    data = _extract_json(raw)
    items: list[DrillItem] = []
    for it in data.get("items") or []:
        if not isinstance(it, dict):
            continue
        sentence = str(it.get("target_sentence", "")).strip()
        corrected = str(it.get("corrected_form", "")).strip()
        error = str(it.get("error_form", "")).strip()
        if sentence and corrected:
            items.append(DrillItem(target_sentence=sentence, corrected_form=corrected, error_form=error))
        if len(items) >= NUM_ITEMS:
            break
    return items


def _normalize(text: str) -> str:
    return " ".join(_WORD_RE.findall((text or "").lower()))


def judge_item(item: DrillItem, response_text: str) -> DrillResult:
    """Deterministic per-item verdict (FR-016 / Key Definitions)."""
    words = _WORD_RE.findall(response_text or "")
    if len(words) < _MIN_RESPONSE_WORDS:
        return "incomplete"
    normalized = _normalize(response_text)
    has_corrected = _normalize(item.corrected_form) in normalized
    has_error = bool(item.error_form) and _normalize(item.error_form) in normalized
    return "pass" if (has_corrected and not has_error) else "fail"
